### ISSUE TITLE
ImmuneML galaxy-error in training model

### ISSUE THREAD

**Issue by Genokarma** [uio-bmi/immuneML#169]
cp: cannot stat '/storage/007/dataset_7020_files/result/*': No such file or directory
or 
cp: cannot stat '/result/*': No such file or directory

An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/immuneml/immuneml_tools/immuneml_train_classifiers/2.2.0.0.

Details
Tool generated the following standard error:

cp: cannot stat '/storage/007/dataset_7020_files/result/*': No such file or directory

**Comment by LonnekeScheffer** [comment]
Dear Genokarma,

I don't have enough understanding about the context in which this error occurred. Were you trying to run immuneML on our Galaxy server (https://galaxy.immuneml.uiocloud.no)? If you are experiencing any issues in Galaxy, you can submit a bug report through the website. This will allow us to take a look into your Galaxy history, to see how the tools were run. Information on how to create a bug report in Galaxy can be found here: https://docs.immuneml.uio.no/latest/galaxy/galaxy_intro.html#viewing-errors-and-reporting-bugs-in-galaxy

Since this issue does not pertain a bug in immuneML, I will close this issue for now. I'd be happy to help you further when you submit the Galaxy bug report.
