### ISSUE TITLE
Matches report with MatchedRegex encoder encountered an error and could not be generated

### ISSUE THREAD

**Issue by KanduriC** [uio-bmi/immuneML#24]
I am trying out the Matches report with MatchedRegex encoding. Please see the attached [log.txt](https://github.com/uio-bmi/immuneML/files/5471006/log.txt) file. It says an error was encountered and no report was created. The [stdout.txt](https://github.com/uio-bmi/immuneML/files/5471037/stdout.txt) file did not show any error. No report was created as stated in the log file. The yaml file ([small_emerson_dat_exploratory_yaml.txt](https://github.com/uio-bmi/immuneML/files/5471004/small_emerson_dat_exploratory_yaml.txt)) and a report-specific motif file ([motif_file.txt (https://github.com/uio-bmi/immuneML/files/5471005/motif_file.txt)) were attached, along with the immuneml imported data ([immuneml_imported_data](https://drive.google.com/drive/folders/1bO2pS6lPQsrQvsxn4etzdaC5fhOgoQXO?usp=sharing)). Could you help me in figuring out what I am doing wrong here? Thanks!

**Comment by BlueBasilisk** [comment]
Thanks! I am a bit busy now but i'll try to take a look tomorrow or the day after

**Comment by BlueBasilisk** [comment]
Hi! I just realized the problem is quite simple. In the yaml specification, you are not specifying the encoding under the instruction, so it is trying to run the report on the data without using encoding. The reason this does not automatically fail is that we have some reports that do accept un-encoded data. However, I do agree there should be more helpful error messages here, which I will add. 
Unfortunately I can not test this with your data because the iml_dataset file is looking for some paths that are specific to your setup.. I'm adding a card to trello to see if we can make those dataset files more reusable and not dependant on file paths. 

Could you let me know once you have tested it if it works?

**Comment by BlueBasilisk** [comment]
@KanduriC unfortunately I can see now that some minor things have changed in some immuneML field names, and the iml_dataset that you are using is now not compatible anymore with the current version of immuneML. If you try to load it, it will complain about the fields named frame_type and region_type. This was changed here: https://github.com/uio-bmi/immuneML/pull/9

If you load the original data from files it should work. Although at some point during testing I got an error related to 'count' being None for some sequences in the 21st repertoire, but I wasn't able to replicate it. So this might be good to double check.

**Comment by BlueBasilisk** [comment]
error messages have been improved here: https://github.com/uio-bmi/immuneML/pull/26

**Comment by KanduriC** [comment]
Thanks @BlueBasilisk for the solutions. I further encountered an error; not clear to me whether it should be a separate issue, but there is some overlap with this thread; so I am continuing here :) . I am attaching an updated yaml instruction file that I am using [small_emerson_dat_exploratory_yaml.txt](https://github.com/uio-bmi/immuneML/files/5479769/small_emerson_dat_exploratory.txt), and the stdout of running that yaml ([Matches_TypeError.txt](https://github.com/uio-bmi/immuneML/files/5479757/Matches_TypeError.txt)) and the [raw data](https://drive.google.com/drive/folders/1IOmeX3y-IalnJkpakByBUnw6k-w2rUvg?usp=sharing) used for this exploratory analysis. I am using a small subset of experimental data from Emerson et al, 2017. 

You mentioned above that you noticed the 'count' being None for some sequences; do you know if the error that I am seeing is related to that?  If yes, do you have any suggestion on what to do about it? Should I preprocess/clean/filter experimental data before importing into immuneML?

**Comment by BlueBasilisk** [comment]
I downloaded one file HIP17449.tsv and tried to run it, and encountered the same error because the amino acid sequence was empty. I found the offending line in the file (line 178382) and the amino acid sequence it contains is "CR" (which, after trimming away the first and last amino acid, becomes an empty string..), there were some other cases as well of the amino acid sequence containing just 1 or 2 characters. This is of course a bit weird, so I will take care of it in the import (remove all empty sequences). I'll let you know when it is on master.

**Comment by BlueBasilisk** [comment]
Oh and I see I did not address your comment about count being none: I adjusted the MatchedRegexEncoder to ignore sequences with none-counts (it will just print a warning saying the sequence was ignored), so that should not be a problem in any case. But if it would later pose an issue with other analyses,  there is a filter for that (CountPerSequenceFilter with the remove_without_count option).

**Comment by KanduriC** [comment]
Thanks @BlueBasilisk ! the same error that I mentioned in my previous message persisted even after pulling the latest fixes, which is on master now.

**Comment by BlueBasilisk** [comment]
Are you able to see which file/repertoire is causing the problem? After I made the fix I tested it with one file (HIP17449.tsv) and that worked without issues. I am now downloading the whole dataset but it's taking a while

**Comment by KanduriC** [comment]
Oh my bad @BlueBasilisk ! I do not get the error now after re-running. Apologies. In my previous attempt, I've not deleted the files in the result path (immuneml imported files) of prior runs; and that would have been the culprit. Thanks for the fix; I was able to look at the report - this is what I need 🙏  .

**Comment by BlueBasilisk** [comment]
great! I'm glad that it works now :)
